### ISSUE TITLE
boolean constructor for some attributes

### ISSUE THREAD

**Issue by willoma** [willoma/bulma-gomponents#10]
For attributes active, selected, etc, currently we have two possibilities (example with b.Option):

- either use b.Option or b.OptionSelected depending on the selected value we need
- or use gomponents.If to add an attribute

What about having something like b.Selected(bool), which would then add attribute "Selected" when the boolean is true, which would be slightly simpler than using gomponents.If?

**Comment by chrismalek** [comment]
From a user of the library, I think `b.Selected(bool)` would be cleaner. I am slowly building an app with this and having to switch between the gomponents library and yours is "messy". (very technical term 😄 ).
