### ISSUE TITLE
Upgrade to maragu.dev/gomponents

### ISSUE THREAD

**Issue by markuswustenberg** [willoma/bulma-gomponents#14]
Hey @willoma! 😊

I'm in the process of moving gomponents to the maragu.dev/gomponents namespace. Could you try upgrading your library to that with `go get maragu.dev/gomponents@v1.0.0-beta1` and see if you hit any issues?

After that, it should simply be a global search/replace in the project: `github.com/maragudk/gomponents` -> `maragu.dev/gomponents`, followed by `go mod tidy`.

I hope you have the time for this, and thank you!

**Comment by willoma** [comment]
Hello!

It seems to work. It is currently located on those different branches:

- [14-upgrade-to-maragudevgomponents](https://github.com/willoma/bulma-gomponents/tree/14-upgrade-to-maragudevgomponents) for the lib
- [docs-upgrade-to-maragudevgomponents](https://github.com/willoma/bulma-gomponents/tree/docs-upgrade-to-maragudevgomponents) for the docs
- [github.com/willoma/gomplements@upgrade-to-maragudevgomponents](https://github.com/willoma/gomplements/tree/upgrade-to-maragudevgomponents) for the gomplements lib

I will leave it like that for now, please inform me when v1.0.0 is released!

**Comment by markuswustenberg** [comment]
Excellent, thanks! I will.

**Comment by markuswustenberg** [comment]
@willoma I've just released v1: https://github.com/maragudk/gomponents/releases/tag/v1.0.0 

Thank you for your work! 😊
