### ISSUE TITLE
Migrate to Bulma v1

### ISSUE THREAD

**Issue by willoma** [willoma/bulma-gomponents#3]

**Comment by chrismalek** [comment]
It looks like Tiles are Deprecated as documented in https://bulma.io/documentation/start/migrating-to-v1/

**Comment by willoma** [comment]
Yes they are. It will disappear in the next version of Bulma-Gomponents, which I'm working on

**Comment by willoma** [comment]
Follow-up: I'm currently working on Bulma v1 support, and at the same time a rewrite of the doc and improving some of the Bulma-Gomponents features.
